# Site settings
baseURL = "https://example.com"
languageCode = "en-US"
title = "Layal Christine Lettry Website"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2022 Layal Christine Lettry"

[params]

  # Metadata for search engines and social sharing
  author = "Layal Christine Lettry"
  description = "Split is a centrally-divided layout for a professional online presence with a big image or video left with alongside content."
  shareImage = "images/background.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Connect"

      [[params.links.list1.link]]
        text = "Github"
        url = "github.com/Layalchristine24"

      [[params.links.list1.link]]
        text = "Email"
        url = "mailto:layal.lettry@gmail.com"

      [[params.links.list1.link]]
        text = "Newsletter"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Social"

      [[params.links.list2.link]]
        text = "Twitter"
        url = "https://twitter.com/LettryL"

      [[params.links.list2.link]]
        text = "Linkedin"
        url = "https://www.linkedin.com/in/layal-christine-lettry-529b4471/"


  # Links List #3
  [[params.links]]
    [params.links.list3]
      heading = "Research"

      [[params.links.list3.link]]
        text = "ResearchGate"
        url = "www.researchgate.net/profile/Layal-Lettry"

      [[params.links.list3.link]]
        text = "Academia"
        url = "unifr.academia.edu/LayalChristineLettry"

    

  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split
