name: CI
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Build Hugo example site and archive output
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2

      - name: Build Hugo example site
        run: |
          cd exampleSite
          hugo --verbose --baseURL= --themesDir=../../

      - name: Archive Hugo example site
        uses: actions/upload-artifact@v2
        with:
          name: hugo-example-site
          path: exampleSite/public
